import Head from 'next/head'
import {useRouter} from 'next/router'
import Avatar from '../Components/Avatar'
import { MicrophoneIcon, MoonIcon, SearchIcon, SunIcon, ViewGridIcon } from '@heroicons/react/solid'
import { useTheme } from 'next-themes';
import { useEffect, useRef, useState } from 'react';
import Footer from '../Components/Footer';
import Header from '../Components/Header';


export default function Home() {

  const router = useRouter();
  
  const searchInputRef = useRef(null);
  

const search = e =>{
e.preventDefault();
const term = searchInputRef.current.value;

if(!term) return;

router.push(`/search?term=${term}`);

};
  
  return (
    <div className="flex flex-col justify-between h-screen ">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.icons8.com/color/452/google-logo.png" />
      </Head>
    
      <Header/>

          <form className="flex flex-col mt-36 items-center  flex-grow">

        <img
          loading="lazy"
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          width="300" height="100"
          alt="Google Icon"
        />


        <div className={`flex w-4/5 mt-5 pt-3 pb-3 pr-5 pl-5 rounded-full border-2 border-[#dfe1e5] hover:shadow-lg focus-within:shadow-lg max-w-lg dark:bg-[#f8f9fa]`}>
         
        <SearchIcon className="h-6 pr-2 text-gray-500"/>
         <input ref={searchInputRef} type="text" className={`flex-grow focus:outline-none dark:text-gray-800 dark:bg-[#f8f9fa]`}/>
         <MicrophoneIcon className="h-6 pl-2 text-gray-500"/> 
        </div>
        <div>
        <button className="btn" onClick={search}>Google Search</button>
        <button className="btn" onClick={search}>I'm Feeling Lucky</button>
        </div>
      </form>

          <Footer/>
      </div>
  )
}
